# https://taskfile.dev

version: '3'

includes:
  OS:
    taskfile: ./Taskfile_{{OS}}.yml
    internal: true

vars:
  APP_NAME: cloc-dir

tasks:
  default:
    cmds:
      - task: build
  run:
    deps: [ build ]
    dir: cmd/cloc-dir
    cmds:
      - ./{{.APP_NAME}}{{exeExt}} -lang Go -dir ../
  build:
    dir: cmd/cloc-dir
    cmds:
      - go build -o {{.APP_NAME}}{{exeExt}} .
    sources:
      - ./*.go
    generates:
      - ./{{.APP_NAME}}{{exeExt}}
  get-cloc:
    cmds:
      - task: OS:download-cloc